### ISSUE TITLE
Develop NASA/PDS Skin for Search API Swagger interface

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#194] opened 2022-06-09 19:30 UTC
## 💡 Description

Details TBD with help/input from @tloubrieu-jpl @jimmie for documentation on how to update this.

**Comment by tloubrieu-jpl** [comment] 2022-06-14 20:21
@tloubrieu-jpl will provide inputs he found on the web

**Comment by tloubrieu-jpl** [comment] 2022-06-14 21:36
@c-suh @al-niessner 

To change the skin of the swagger-ui page, here is the procedure I was thinking of from what I search online:

- We need to override the css and/or html page content in one springfox jar that we use to build the application
References:
https://stackoverflow.com/questions/66704031/how-to-change-swagger-ui-index-html-logo-and-header-contents-in-springfox
https://github.com/springfox/springfox/issues/1108
https://github.com/swagger-api/swagger-ui/issues/4390


- We can update the jar file during the build process, in maven (see Patch the jar
https://gist.github.com/afrische/aa5cad210b637e2b5291)






What to update in the jar

**Comment by c-suh** [comment] 2022-06-30 21:45
@tloubrieu-jpl, @jordanpadams, @viviant100, or @jimmie, is there documentation somewhere on where we have these deployed or how to do it locally? I found personal notes on how to connect to the validation API on dev 3 via ssh tunnel, but I'm getting "Connection refused" messages inn my terminal. I also searched through our internal wiki but have missed it if it's there. Thank you in advance!

**Comment by tloubrieu-jpl** [comment] 2022-07-05 21:02
@c-suh I just merged an update of registry-api in branch https://github.com/NASA-PDS/registry-api/tree/release/1.0.1 which fixes the swagger-ui page.

**Comment by c-suh** [comment] 2022-07-12 20:52
During breakout, have figured out how to get elasticsearch running. Have instructions on how to get dev environment set up and will be attempting that.

**Comment by c-suh** [comment] 2022-07-14 21:01
Have successfully run `mvn clean install` with registry-api with jdk11 (attempt with jdk17 failed) and started spring-boot. Am now locating files for the page.

**Comment by c-suh** [comment] 2022-07-26 20:10
Am momentarily delayed by having to set up environments on another laptop.

**Comment by c-suh** [comment] 2022-08-08 23:27
Got everything set up again then was sidetracked by other tasks. Am back on this and have finally got the swagger-ui showing. There was an issue caused by a mismatch between registry-api-model and registry-api-service in their springfox-version. Have noticed that the swagger-ui for this is different from that which shows with registry's int-registry-service-loader and will ask at tomorrow's meeting if this should be addressed.

**Comment by c-suh** [comment] 2022-08-25 16:50
Back from vacation and being sick. Issue mentioned above is now null because Al fixed it. Back on track with original task.

**Comment by jimmie** [comment] 2022-09-01 21:13
Further investigation on behavior prior to making changes.

**Comment by c-suh** [comment] 2022-09-09 20:54
I think I've finally managed to piece together some understanding of how this works. I've disabled springfox 3's default swagger-ui and have my own swagger-ui files running with the application. Next steps are to find an optimal place to change the logo and styling, package these into a jar, integrate this into maven's build process, and to verify that I haven't compromised any use of swagger's security that the other developers may be making use of.

**Comment by jordanpadams** [comment] 2022-09-10 23:18
@c-suh let us know if you need any assistance. it would be great if this could be done by our sprint review next Thursday.

**Comment by c-suh** [comment] 2022-09-13 21:30
There seem to be 2 methods:
- disabling springfox documentation, dropping in contents of swagger-ui repo, and resource mapping to use those files
- using springfox documentation, unpacking the springfox-swagger-ui jar, and overwriting a few relevant files
I'm not sure of the advantage of the latter option, and I have the former working (latter is only partially working). Have talked with Jimmie and the decision is to continue with the working route and get a better idea of what exactly can be customized and not (e.g. footer, menu button).

**Comment by c-suh** [comment] 2022-09-16 17:26
Thanks to Jimmie, this look is merged into the `main` branch!
![nasa-pds-swagger](https://user-images.githubusercontent.com/18314609/190696789-2fd2e31c-87b4-41e3-82fb-ed84ce87da4a.jpg)

**Closed by c-suh** 2022-09-16 17:26 UTC
Labels: B13.0, sprint-backlog, task

**Comment by jimmie** [comment] 2022-09-27 17:26
Sorry, I just found this and a few other legitimate messages in my spam folder. Wasn't this email migration supposed to be a good thing?

Anyways, all the credit goes to you as the one who did all the heavy lifting in this scenario! Although, I did fix that lower case 'f' for Federated. I feel so tired now.

j

From: Catherine Suh ***@***.***>
Date: Friday, September 16, 2022 at 10:26 AM
To: NASA-PDS/pds-api ***@***.***>
Cc: Jimmie Young ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-PDS/pds-api] Develop NASA/PDS Skin for Search API Swagger interface (Issue #194)

Thanks to Jimmie, this look is merged into the main branch!
[nasa-pds-swagger]<https://urldefense.us/v3/__https:/user-images.githubusercontent.com/18314609/190696789-2fd2e31c-87b4-41e3-82fb-ed84ce87da4a.jpg__;!!PvBDto6Hs4WbVuu7!ae-uMxEzHqjpYbYLBvDRDvPICaBSAJcheWdXSK0S-5Z7ZufEAPMPqPTCTSlMx2_AGzxc$>

**Comment by tloubrieu-jpl** [comment] 2022-11-30 02:09
@jimmie @jordanpadams does that mean we could forward with the publication of the swagger web  page. Note that I am not seeing the nasa logo on my integration deployment here, but this is a detail that we can look at later.

**Comment by jordanpadams** [comment] 2022-11-30 02:13
@tloubrieu-jpl I think so? But now that I think about it, I've never seen a demo of this.

@c-suh have you demoed this? And if not, can you demo how to make this at the sprint review?

**Comment by miguelp1986** [comment] 2023-02-11 06:28
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4212027

**Comment by gxtchen** [comment] 2023-04-15 19:54
This use to work in system-i-n-t 30, but now I don't see the jpl skin using registry docker.

**Comment by jordanpadams** [comment] 2023-04-17 00:17
@tloubrieu-jpl @miguelp1986 @ramesh-maddegoda @alexdunnjpl any input here?

**Comment by gxtchen** [comment] 2023-04-17 06:40
my bad, works after purging docker images.
