### ISSUE TITLE
As an API user, I want to know the Product(s) that belong to a given Collection.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#58] opened 2021-03-26 17:52 UTC
For more information on how to populate this new feature request, see the PDS Wiki on User Story Development:

https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Issue-Tracking#user-story-development

## Motivation
...so that I can <why do you want to do this?>

## Additional Details
Notional API Design:
```
GET /collections/{lidvid}/products
```

See https://github.com/NASA-PDS/pds-registry-app/issues/144 and https://github.com/NASA-PDS/pds-registry-app/issues/143 for how the registry ingests primary and secondary products.

## Acceptance Criteria
**Given** I have a collection LID OR LIDVID
**When I perform** an API query by that LID/LIDVID for its products
**Then I expect** the API to return the primary product(s) AND any secondary product(s) for that collection

## Sub-tasks
- [ ] Update Swagger API
- [ ] Implement in API Server

**Comment by tloubrieu-jpl** [comment] 2021-04-19 18:45
This ticket is a duplicate of https://github.com/NASA-PDS/registry-api-service/issues/2

**Closed** 2021-11-18 18:57 UTC
Labels: duplicate, requirement, B12.0, p.must-have, sprint-backlog
