### ISSUE TITLE
As an API user, I want to be able to use wildcard or like operator when apply filter queries

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#63] opened 2021-03-29 17:01 UTC
See specification https://docs.google.com/document/d/16d0MVh48bFLvWsa5-B_Hy-cby1rGWdnNojWOJpUcOvA/edit#heading=h.dihrtzltiwag

**Comment by jordanpadams** [comment] 2021-03-29 18:01
duplicate of #54

**Closed by jordanpadams** 2021-03-29 18:01 UTC
Labels: duplicate, needs:triage, requirement
